name: mylists
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qidgets:
    git:
      url: https://github.com/epatel/flutter_qidgets.git
      ref: c6394d573ea0d9f2265c68c2ee040d45dfaf0787

  cupertino_icons: ^1.0.2
  printing: ^5.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
